### ISSUE TITLE
error when adding/modifying issue

### ISSUE THREAD

**Issue by piccio** [rsvargas/redmine_email_fiddler#1]
Is raised an error when adding an issue
```
NoMethodError (undefined method `project' for #<Array:0x007f1ce479bfa0>):
  plugins/email_fiddler/lib/mailer_patch.rb:21:in `block in mail_fiddler_format'
  plugins/email_fiddler/lib/mailer_patch.rb:18:in `gsub'
  plugins/email_fiddler/lib/mailer_patch.rb:18:in `each'
  plugins/email_fiddler/lib/mailer_patch.rb:18:in `mail_fiddler_format'
  plugins/email_fiddler/lib/mailer_patch.rb:41:in `issue_add_with_fiddle'
  app/models/mailer.rb:497:in `initialize'
  config/initializers/10-patches.rb:163:in `deliver'
  app/models/mailer.rb:64:in `block in deliver_issue_add'
  app/models/issue.rb:1055:in `block in each_notification'
  app/models/issue.rb:1054:in `each'
  app/models/issue.rb:1054:in `each_notification'
  app/models/mailer.rb:63:in `deliver_issue_add'
  app/models/issue.rb:1845:in `send_notification'
  app/models/issue.rb:210:in `create_or_update'
  app/controllers/issues_controller.rb:129:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
and also when modifying an issue
```
NoMethodError (undefined method `journalized' for #<Array:0x007f1ce63015b0>):
  plugins/email_fiddler/lib/mailer_patch.rb:54:in `issue_edit_with_fiddle'
  app/models/mailer.rb:497:in `initialize'
  config/initializers/10-patches.rb:163:in `deliver'
  app/models/mailer.rb:98:in `block (2 levels) in deliver_issue_edit'
  app/models/issue.rb:1055:in `block in each_notification'
  app/models/issue.rb:1054:in `each'
  app/models/issue.rb:1054:in `each_notification'
  app/models/mailer.rb:97:in `block in deliver_issue_edit'
  app/models/journal.rb:105:in `block in each_notification'
  app/models/journal.rb:103:in `each'
  app/models/journal.rb:103:in `each_notification'
  app/models/mailer.rb:96:in `deliver_issue_edit'
  app/models/journal.rb:325:in `send_notification'
  app/controllers/issues_controller.rb:546:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:168:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

it appears that the arguments in the methods `#issue_add_with_fiddle` and `#issue_edit_with_fiddle` have always at the first position an `issue` object or a `journal` object, respectively

my redmine version is 3.4.4.stable

redmine code:
```ruby
  # Builds a mail for notifying to_users and cc_users about a new issue
  def issue_add(issue, to_users, cc_users)
```
```ruby
  # Builds a mail for notifying to_users and cc_users about an issue update
  def issue_edit(journal, to_users, cc_users)
```

**Comment by rsvargas** [comment]
This was introduced when changing to be compatible with Redmine 4.0. Created a tag: [redmine_3_x](https://github.com/rsvargas/redmine_email_fiddler/tree/redmine_3_x), pointing to the last revision that was compatible for you to be able to track directly.
